### ISSUE TITLE
smregtest fail

### ISSUE THREAD

**Issue by lorenzoperone** [marekrei/smuploader#8]
I've follow the tips and 'smregister' was well done but when I digit

`smregtest`

I recive this message of error

```
REQUEST:
method=GET
url=https://api.smugmug.com/api/v2/user/myuser@gmail.com!albums
params={'count': 500, 'start': 1}
headers={'Accept': 'application/json'}
data=None
RESPONSE DATA:
{"Response":{"Uri":"/api/v2/user/myuser@gmail.com!albums?count=500&oauth_nonce=XXXXXXXX ... riDescription":"All of user's albums","EndpointType":"UserAlbums"},"Code":404,"Message":"Not Found"}
Retrying (1)...
Error: Too many retries, giving up.
E
======================================================================
ERROR: test_album_creation (__main__.TestSmugMug)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lorenzo/.local/bin/smregtest", line 12, in test_album_creation
    albums = smugmug.get_album_names()
  File "/home/lorenzo/.local/lib/python2.7/site-packages/smuploader/smugmug.py", line 147, in get_album_names
    albums = self.get_albums()
  File "/home/lorenzo/.local/lib/python2.7/site-packages/smuploader/smugmug.py", line 132, in get_albums
    response = self.request('GET', self.smugmug_api_base_url + "/user/"+self.username+"!albums", params=params, headers={'Accept': 'application/json'})
  File "/home/lorenzo/.local/lib/python2.7/site-packages/smuploader/smugmug.py", line 119, in request
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 1 test in 27.660s

FAILED (errors=1)

````
I hope in you :)

**Comment by marekrei** [comment]
I have just fixed an issue involving an API change, that caused errors in smregtest.
This specific issue seems to be the API timing out though, which could be due to a temporary API issue or ratelimiting. 

I'm not able to replicate it at the moment. If you are still experiencing the issue, let me know.
